cp ../template.cpp A.cpp
cp ../template.cpp B.cpp
cp ../template.cpp C.cpp
cp ../template.cpp D.cpp
cp ../template.cpp E.cpp
cp ../template.cpp F.cpp
cp ../template.cpp G.cpp
cp ../template.cpp H.cpp
cp ../template.cpp I.cpp
cp ../template.cpp J.cpp
cp ../template.cpp K.cpp
cp ../template.cpp L.cpp
